apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sharry
  namespace: user5-sharry
spec:
  host: sharry-user5-sharry.apps.ocp4.janz.cloud
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sharry
    weight: 100
  wildcardPolicy: None